hmrc/ers-returns-frontend

app/views/csv_file_upload.scala.html, app/views/file_upload.scala.html, app/views/unauthorised.scala.html, conf/messages
DDCNLS-1554 : Ers-returns-frontend msg file refactor
=> DDCNLS-1554 : Ers-returns-frontend msg file refactor 

conf/messages, test/controllers/ApplicationControllerSpec.scala
@nehakannaujia - I have reviewed contractions etc., and I've updated the tests where necessary.
=> DDCNLS-1555

app/config/ApplicationConfig.scala, app/views/confirmation.scala.html, app/views/ers_main.scala.html, app/views/helpers/fullWidthBanner.scala.html, app/views/helpers/fullWidthBannerContentUr.scala.html, app/views/main.scala.html, conf/application.conf, conf/messages, public/javascripts/urBanner.js, public/stylesheets/urBanner.css, test/controllers/ConfirmationPageControllerTest.scala
DDCNLS-2751: Added UR banner on confirmation page
=> DDCNLS-2751: Added UR banner on confirmation page

repository.yaml
This will prevent alerts to #event-github-alert when making commits to this branch
=> Added LDS exemption for test file

app/controllers/SummaryDeclarationController.scala, test/controllers/AltAmendsControllerTest.scala, test/controllers/CheckCsvFilesControllerSpec.scala, test/controllers/CheckFileTypeControllerTest.scala, test/controllers/ConfirmationPageControllerTest.scala, test/controllers/GeneratePdfControllerSpec.scala, test/controllers/GroupSchemeControllerTest.scala, test/controllers/ReportableEventsControllerTest.scala, test/controllers/ReturnServiceControllerTest.scala, test/controllers/SchemeOrganiserControllerTest.scala, test/controllers/SubmissionDataControllerSpec.scala, test/controllers/SummaryDeclarationControllerTest.scala, test/controllers/TrusteeControllerTest.scala, test/utils/AuthHelper.scala, test/utils/ERSFakeApplicationConfig.scala
Some of the tests only passed if you had auth running in service manager. I've re ran the tests with  nothing running at all and they pass now. Should go through pipeline now.
=> DDCE-75: Added missing mocks to tests

app/controllers/Authenticator.scala, app/controllers/ReturnServiceController.scala, app/utils/CacheUtil.scala, test/controllers/ReturnServiceControllerTest.scala, test/utils/CacheUtilSpec.scala
Replicated the issue in QA and locally, problem is fixed.
Cause was surrounding agents trying to retrieve data that hadn't been cached yet.
=> DDCE-75: Fixed caching permissions issue

app/views/upscan_ods_file_upload.scala.html, conf/messages.cy, conf/messages.en, public/stylesheets/ers_styles.css
Updated content as required in the ticket description.
=> [RS][DDCE-858] Updating content on ODS file upload.

app/config/ApplicationConfig.scala, conf/application.conf
- Fixing the user of base-url instead of host for contact frontend.
- Included the changes from here - https://github.com/hmrc/ers-returns-frontend/pull/89
- Removed deny list.
=> DDCE-923: Fixed get help form not working

conf/application.conf, project/FrontendBuild.scala
Added the acccessibitlity statement config and update play ui version
=> DDCE-1083: added the accessibility statement config

app/views/check_csv_file.scala.html, conf/messages.cy, conf/messages.en, project/FrontendBuild.scala, project/plugins.sbt
##New feature
As per the change request, hint text has been added to the /choose-csv-files page to help users better understand which options they need to choose. Approved by WLU.
=> [EH][DDCE-857] Added hint to /choose-csv-files

project/plugins.sbt
##Bug fix
Reverted failing dependency: sbt-artifcatory from 1.6.0 to 1.5.0
=> DDCE-857: Reverted sbt-artifactory version

app/views/alterations_activity.scala.html, app/views/alterations_amends.scala.html, app/views/check_csv_file.scala.html, app/views/check_file_type.scala.html, app/views/confirmation.scala.html, app/views/group.scala.html, app/views/group_plan_summary.scala.html, app/views/helpers/error_overview.scala.html, app/views/includes/upscan_file_upload_form.scala.html, app/views/manual_company_details.scala.html, app/views/reportable_events.scala.html, app/views/scheme_organiser.scala.html, app/views/start.scala.html, app/views/trustee_details.scala.html, app/views/trustee_summary.scala.html, app/views/upscan_csv_file_upload.scala.html, app/views/upscan_ods_file_upload.scala.html, conf/application.conf, public/javascripts/ers_csv_scripts.js, public/javascripts/ers_ods_scripts.js, public/javascripts/ers_scripts.js, public/stylesheets/ers_styles.css
Updated the services frontend to use the newer assets
=> DDCE-622: updated assets frontend to v3.11

app/connectors/UpscanConnector.scala
##Bug fix
Removed the agent name from the upscan connector which was adding a duplicate service name causing the call to fail
=> removed agent header name from upscan connector

app/config/ApplicationConfig.scala, app/views/main.scala.html, conf/application.conf
I haven't included dependency updates because that will be included as part of the play 2.6 story that's already in progress.
=> DDCE-1075: Added GTM snippet

app/controllers/LanguageSwitchController.scala
##Bug fix / New feature (delete as appropriate)
=> DDCE-1273:Open Redirect vulnerability fix

app/views/summary.scala.html
##Bug fix / New feature (delete as appropriate)
=> DDCE-1319: HTML table element changed from td to th

app/views/summary.scala.html, project/AppDependencies.scala
=> DDCE-1321: Added spans to Summary page for screen reader clarity

app/controllers/CsvFileUploadController.scala
=> [EH][DDCE-1606] Log Change

README.md
=> DDCE-1639: updated readme with relevant information

app/controllers/auth/AuthFunctionality.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/controllers/auth/AuthFunctionalitySpec.scala
=> DDCE-1115 - Fix the government-gateway-sign-in link for ers-returns-frontend

app/views/reportable_events.scala.html
DDCE-2899 - /reportable-events error should link to first input field
=> DDCE-2899 - /reportable-events error should link to first input field

app/views/alterations_activity.scala.html, app/views/alterations_amends.scala.html, app/views/check_csv_file.scala.html, app/views/check_file_type.scala.html, app/views/govuk_wrapper.scala.html, app/views/group.scala.html, app/views/group_plan_summary.scala.html, app/views/manual_company_details.scala.html, app/views/reportable_events.scala.html, app/views/scheme_organiser.scala.html, app/views/summary.scala.html, app/views/trustee_details.scala.html, app/views/trustee_summary.scala.html, app/views/upscan_csv_file_upload.scala.html, app/views/upscan_ods_file_upload.scala.html
Refactored - added iebacklink.js call to govuk_wrapper.
Back button takes the user back to the previous location they visited throughout the service.
=> Apply back button logic to ers-returns-frontend

app/views/alterations_activity.scala.html, app/views/alterations_amends.scala.html, app/views/check_csv_file.scala.html, app/views/check_file_type.scala.html, app/views/govuk_wrapper.scala.html, app/views/group.scala.html, app/views/group_plan_summary.scala.html, app/views/manual_company_details.scala.html, app/views/reportable_events.scala.html, app/views/scheme_organiser.scala.html, app/views/summary.scala.html, app/views/trustee_details.scala.html, app/views/trustee_summary.scala.html, app/views/upscan_csv_file_upload.scala.html, app/views/upscan_ods_file_upload.scala.html
Reverts hmrc/ers-returns-frontend#148
=> Revert "Apply back button logic to ers-returns-frontend"

app/views/govuk_wrapper.scala.html, app/views/group.scala.html, app/views/manual_company_details.scala.html, app/views/scheme_organiser.scala.html, app/views/trustee_details.scala.html, app/views/trustee_summary.scala.html
=> Apply back button logic for company-details and subsidiary-company

repository.yaml
-  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
-  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
-  I've squashed my commits - including the JIRA issue number in the commit message
-  I've run a dependency check to ensure all dependencies are up to date
=> leak detection is removed

app/controllers/AltAmendsController.scala, app/controllers/ApplicationController.scala, app/controllers/CheckCsvFilesController.scala, app/controllers/CheckFileTypeController.scala, app/controllers/GroupSchemeController.scala, app/controllers/ReportableEventsController.scala, app/controllers/SchemeOrganiserController.scala, app/controllers/TrusteeController.scala, app/services/pdf/ErsReceiptPdfBuilderService.scala, build.sbt, conf/messages.cy, conf/messages.en, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/controllers/ApplicationControllerSpec.scala, test/controllers/ConfirmationPageControllerSpec.scala, test/controllers/SubmissionDataControllerSpec.scala, test/utils/ErsTestHelper.scala
Also adjusted the logging of the pdf-creation library being used.
=> [DP][DDCE-3067] Bootstrap & sbt upgrades

a11y/FrontendAccessibilitySpec.scala, app/controllers/trustees/TrusteeRemoveController.scala, app/controllers/trustees/TrusteeRemoveProblemController.scala, app/controllers/trustees/TrusteeSummaryController.scala, app/forms/YesNoFormProvider.scala, app/services/TrusteeService.scala, app/utils/DateUtils.scala, app/utils/ERSUtil.scala, app/views/trustee_remove_problem.scala.html, app/views/trustee_remove_yes_no.scala.html, app/views/trustee_summary.scala.html, build.sbt, conf/app.routes, conf/messages.cy, conf/messages.en, project/plugins.sbt, test/controllers/trustees/TrusteeAddressOverseasSpec.scala, test/controllers/trustees/TrusteeAddressUkSpec.scala, test/controllers/trustees/TrusteeRemoveControllerSpec.scala, test/controllers/trustees/TrusteeRemoveProblemControllerSpec.scala, test/controllers/trustees/TrusteeSummaryControllerSpec.scala, test/forms/YesNoFormProviderTest.scala, test/services/TrusteeServiceSpec.scala, test/utils/Fixtures.scala
=> DDCE-4962 | Improved delete trustee flow.

app/controllers/ConfirmationPageController.scala, app/models/ErsSummary.scala, app/models/RSformModels.scala, app/services/FrontendSessionService.scala, app/services/audit/AuditService.scala, app/utils/CacheHelper.scala, app/utils/DateUtils.scala, app/utils/HMACUtil.scala, project/AppDependencies.scala, project/plugins.sbt, test/connectors/ERSConnectorSpec.scala, test/controllers/ConfirmationPageControllerSpec.scala, test/controllers/CsvFileUploadControllerSpec.scala, test/controllers/FileUploadControllerSpec.scala, test/controllers/GeneratePdfControllerSpec.scala, test/controllers/ReportableEventsControllerSpec.scala, test/controllers/ReturnServiceControllerSpec.scala, test/controllers/SummaryDeclarationControllerSpec.scala, test/controllers/auth/AuthFunctionalitySpec.scala, test/controllers/trustees/TrusteeSummaryControllerSpec.scala, test/models/RequestObjectSpec.scala, test/services/ErsReceiptPdfBuilderServiceSpec.scala, test/services/audit/AuditEventsTest.scala, test/services/pdf/PdfDecoratorControllerFactorySpec.scala, test/utils/Fixtures.scala
=> DDCE-5060: Move to using Java time

app/connectors/ErsConnector.scala, app/controllers/CheckCsvFilesController.scala, app/controllers/CsvFileUploadController.scala, app/controllers/auth/AuthFunctionality.scala, app/controllers/schemeOrganiser/SchemeOrganiserBaseController.scala, app/controllers/subsidiaries/GroupSchemeController.scala, app/controllers/subsidiaries/SubsidiaryBaseController.scala, app/controllers/trustees/TrusteeBaseController.scala, app/controllers/trustees/TrusteeRemoveController.scala, app/controllers/trustees/TrusteeSummaryController.scala, app/services/CompanyDetailsService.scala, app/services/FrontendSessionService.scala, conf/application.conf, project/AppDependencies.scala, test/services/pdf/ErsPdfReaderSpec.scala
- improve logs
- update bootstrap play
=> DDCE-6057: upgrade bootstrap play, improve loggers

conf/application.conf
DDCE-6367: update file size limit to 100MB in local
=> DDCE-6367: update file size limit to 100MB in local

app/controllers/ConfirmationPageController.scala, app/controllers/CsvFileUploadController.scala, app/services/UpscanService.scala, project/AppDependencies.scala
=> DDCE-6835: remove unsafe logs
